#!/bin/bash

if [ "$USER" != "mqm" ]
then
   echo "Run script as mqm whih command: sudo su - mqm"
   exit 4
fi

# Set path

export PATH=${PATH}:/opt/mqm/bin

# End and delete old QMGRs

endmqm -w QMA
dltmqm QMA

endmqm -w QMB
dltmqm QMB

# Create QMGR QMA and its objects

crtmqm QMA
strmqm QMA

cat <<EOF | runmqsc QMA
DEFINE LISTENER('QMA.LST') TRPTYPE(TCP) PORT(14001) CONTROL(QMGR)
START  LISTENER('QMA.LST')
DEFINE CHANNEL('QMA.QMB') CHLTYPE(SDR) CONNAME('127.0.0.1(14002)') TRPTYPE(TCP) XMITQ('QLX.QMB')
DEFINE CHANNEL('QMB.QMA') CHLTYPE(RCVR) TRPTYPE(TCP)
DEFINE CHANNEL('CHL.SVR') CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL('QLO.A') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) 
DEFINE QLOCAL('QLX.QMB') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) USAGE(XMITQ)
DEFINE QREMOTE('QRE.B') DEFPSIST(YES) RNAME('QLO.B') RQMNAME('QMB') XMITQ('QLX.QMB')
SET AUTHREC PROFILE('SELF') PRINCIPAL('maralion') OBJTYPE(QMGR) AUTHADD(ALTUSR,CHG,CONNECT,DLT,DSP,INQ,SET,SETALL,SETID,CTRL,SYSTEM)
SET AUTHREC PROFILE('QLO.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
SET AUTHREC PROFILE('QRE.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
EOF

# Create QMGR QMB and its objects

crtmqm QMB
strmqm QMB

cat <<EOF | runmqsc QMB
DEFINE LISTENER('QMB.LST') TRPTYPE(TCP) PORT(14002) CONTROL(QMGR)
START  LISTENER('QMB.LST')
DEFINE CHANNEL('QMB.QMA') CHLTYPE(SDR) CONNAME('127.0.0.1(14001)') TRPTYPE(TCP) XMITQ('QLX.QMA')
DEFINE CHANNEL('QMA.QMB') CHLTYPE(RCVR) TRPTYPE(TCP)
DEFINE CHANNEL('CHL.SVR') CHLTYPE(SVRCONN) TRPTYPE(TCP)
DEFINE QLOCAL('QLO.B') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) 
DEFINE QLOCAL('QLX.QMA') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) USAGE(XMITQ)
DEFINE QREMOTE('QRE.A') DEFPSIST(YES) RNAME('QLO.A') RQMNAME('QMA') XMITQ('QLX.QMA')
SET AUTHREC PROFILE('SELF') PRINCIPAL('maralion') OBJTYPE(QMGR) AUTHADD(ALTUSR,CHG,CONNECT,DLT,DSP,INQ,SET,SETALL,SETID,CTRL,SYSTEM)
SET AUTHREC PROFILE('QLO.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
SET AUTHREC PROFILE('QRE.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
EOF

# Start channels between QMA and QMB

echo "START CHANNEL('QMA.QMB')" | runmqsc QMA
echo "START CHANNEL('QMB.QMA')" | runmqsc QMB

# Wait a few seconds in order to get channels running

sleep 4

# Display channels status

echo "DISPLAY CHSTATUS('*')" | runmqsc QMA
echo "DISPLAY CHSTATUS('*')" | runmqsc QMB

exit 0

