#!/bin/bash

if [ "$USER" != "mqm" ]
then
   echo "Run script as mqm whih command: sudo su - mqm"
   exit 4
fi

# Set path

export PATH=${PATH}:/opt/mqm/bin

# End and delete old QMGR

endmqm -i QMA
dltmqm QMA

# Create QMGR QMA and its objects

crtmqm QMA
strmqm QMA

cat <<EOF | runmqsc QMA
DEFINE LISTENER('QMA.LST') TRPTYPE(TCP) PORT(14001) CONTROL(QMGR)
START  LISTENER('QMA.LST')
DEFINE CHANNEL('CHL.SVR') CHLTYPE(SVRCONN) TRPTYPE(TCP) SCYEXIT('scyexit_chnlstartq(scyexit)') SCYDATA('QLO.SCYEXIT.STAT')
DEFINE QLOCAL('QLO.A') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) 
DEFINE QLOCAL('QLO.SCYEXIT.STAT') DEFPSIST(YES) DISTL(NO) MAXDEPTH(5000) 
SET AUTHREC PROFILE('SELF') PRINCIPAL('maralion') OBJTYPE(QMGR) AUTHADD(ALTUSR,CHG,CONNECT,DLT,DSP,INQ,SET,SETALL,SETID,CTRL,SYSTEM)
SET AUTHREC PROFILE('QLO.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
SET AUTHREC PROFILE('QRE.**') PRINCIPAL('maralion') OBJTYPE(QUEUE) AUTHADD(BROWSE,CHG,CLR,DLT,DSP,GET,INQ,PUT,PASSALL,PASSID,SET,SETALL,SETID) 
EOF

exit 0

